services:
  backend:
    image: docker.io/learnedmachine/ink2md-backend:latest
    container_name: ink2md-backend
    ports:
      - "6201:6201"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
      - TZ=America/Chicago
    volumes:
      - ./ink2md/temp:/app/temp
      - ./config:/app/config
      - ./data:/app/data
      - ./input_pdfs:/app/input_pdfs
      - ./output_markdown:/app/output_markdown
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6201/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: docker.io/learnedmachine/ink2md-frontend:latest
    container_name: ink2md-frontend
    ports:
      - "3000:3000"
    environment: {}
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: ink2md-network
