services:
  backend:
    build:
      context: ./pdf3md
      dockerfile: Dockerfile.backend
    container_name: pdf3md-backend-dev
    ports:
      - "6201:6201"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - TZ=America/Chicago
    volumes:
      - ./pdf3md:/app
      - ./pdf3md/temp:/app/temp
    command: python app.py
    restart: unless-stopped

  frontend:
    image: node:18-alpine
    container_name: pdf3md-frontend-dev
    working_dir: /app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./pdf3md:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: pdf3md-dev-network
