services:
  backend:
    build:
      context: ./ink2md
      dockerfile: Dockerfile.backend
    container_name: ink2md-backend-dev
    ports:
      - "6201:6201"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - TZ=America/Chicago
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./ink2md:/app
      - ./ink2md/temp:/app/temp
      - ./config:/app/config
      - ./data:/app/data
      - ./input_pdfs:/app/input_pdfs
      - ./output_markdown:/app/output_markdown
    command: python app.py
    restart: unless-stopped

  frontend:
    image: node:18-alpine
    container_name: ink2md-frontend-dev
    working_dir: /app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./ink2md:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: ink2md-dev-network
