name: Docker Build and Publish Backend

on:
  push:
    branches: [ "main" ] 
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ] 

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # Update this to your Docker Hub username and desired image name
  IMAGE_NAME: murtaza-nasir/pdf3md-backend

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required for publishing to GitHub Packages if you switch REGISTRY
      id-token: write # Required for OIDC with Sigstore/Fulcio

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: ./pdf3md # Assuming backend Dockerfile context is pdf3md/
          file: ./pdf3md/Dockerfile.backend # Path to your backend Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
